use bevy::prelude::*;

use super::abilities::{AbilityId, CastTarget};

/// How a party member behaves when not given explicit commands.
/// Influences which evaluators are active on the entity's AiBrain.
#[derive(Component, Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum PartyMode {
    #[default]
    Aggressive,
    Defensive,
    Passive,
    Follow,
}

/// Priority levels — higher number = higher priority.
/// Player commands get 100, combat evaluators 50-90, routine 10-30.
pub type TaskPriority = u32;

/// Where a task came from. Determines interruption rules.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TaskSource {
    /// Generated by an evaluator (AI).
    Evaluator,
    /// Explicitly issued by the player.
    Player,
}

/// A single atomic step in a task.
#[derive(Clone, Debug)]
pub enum Action {
    /// Move within range of a target entity.
    MoveToEntity { target: Entity, range: f32 },
    /// Move to a specific tile.
    MoveToPosition { x: u32, y: u32 },
    /// Move away from a threat.
    FleeFrom { threat: Entity },
    /// Stay near another entity.
    FollowEntity { leader: Entity, distance: f32 },
    /// Stay in combat with a target: chase if out of range, auto-attack handles hitting.
    EngageTarget { target: Entity, attack_range: f32 },
    /// Wait for a number of ticks.
    Wait { ticks: u32, elapsed: u32 },
    /// Cast an ability. `initiated` tracks whether CastingState has been inserted.
    CastAbility {
        ability_id: AbilityId,
        slot_index: usize,
        target: CastTarget,
        initiated: bool,
    },
}

/// Status of an individual action's execution.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ActionStatus {
    /// Currently executing.
    Active,
    /// Completed successfully.
    Done,
    /// Failed (target died, path impossible, etc.).
    Failed,
}

/// A piece of work: a sequence of actions to execute.
#[derive(Clone, Debug)]
pub struct Task {
    /// Human-readable label for debugging.
    pub label: &'static str,
    pub priority: TaskPriority,
    pub source: TaskSource,
    /// Ordered list of actions to execute.
    pub actions: Vec<Action>,
    /// Index of the currently active action.
    pub current_action: usize,
    /// Whether this task can be interrupted by a higher-priority evaluator task.
    pub interruptible: bool,
}

impl Task {
    pub fn new(label: &'static str, priority: TaskPriority, source: TaskSource, actions: Vec<Action>) -> Self {
        Self {
            label,
            priority,
            source,
            actions,
            current_action: 0,
            interruptible: true,
        }
    }

    /// Get the currently active action, if any.
    pub fn current(&self) -> Option<&Action> {
        self.actions.get(self.current_action)
    }

    /// Advance to the next action. Returns true if there are more actions.
    pub fn advance(&mut self) -> bool {
        self.current_action += 1;
        self.current_action < self.actions.len()
    }

    /// Whether all actions have been completed.
    pub fn is_finished(&self) -> bool {
        self.current_action >= self.actions.len()
    }
}

// ---------------------------------------------------------------------------
// CurrentTask — "what am I doing right now?" (all active entities)
// ---------------------------------------------------------------------------

/// The entity's current task. Present only when the entity has work to do.
/// Inserted by player input or AI arbitration. Removed by tick_actions on completion/failure.
#[derive(Component, Clone, Debug)]
pub struct CurrentTask(pub Task);

impl CurrentTask {
    pub fn new(task: Task) -> Self {
        Self(task)
    }

    /// Get the currently active action.
    pub fn current_action(&self) -> Option<&Action> {
        self.0.current()
    }

    /// Whether a proposed task should replace this one.
    pub fn should_replace(&self, proposal: &Task) -> bool {
        let current = &self.0;
        // Player tasks can only be replaced by other player tasks
        if current.source == TaskSource::Player && proposal.source != TaskSource::Player {
            return false;
        }
        // Must be interruptible
        if !current.interruptible {
            return proposal.source == TaskSource::Player;
        }
        // Higher priority wins
        proposal.priority > current.priority
    }
}

// ---------------------------------------------------------------------------
// Derived marker — EngageTarget
// ---------------------------------------------------------------------------

/// Derived marker component. Present when the entity's current action is
/// `Action::EngageTarget`. Maintained by `tick_actions`, read by `auto_attack`.
#[derive(Component, Clone, Copy, Debug)]
pub struct Engaging {
    pub target: Entity,
}

// ---------------------------------------------------------------------------
// AiBrain — "how do I decide what to do?" (NPC-only)
// ---------------------------------------------------------------------------

/// Which evaluator category a given evaluator belongs to.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EvaluatorCategory {
    /// Evaluated frequently (~5 ticks). Combat-related decisions.
    Combat,
    /// Evaluated less frequently (~60 ticks). Patrol, follow, idle.
    Routine,
}

/// An evaluator type. Each variant knows how to check conditions and propose a Task.
#[derive(Clone, Debug, PartialEq)]
pub enum TaskEvaluator {
    /// Scan for hostiles, check threat table. Proposes [EngageTarget].
    EngageCombat,
    /// Check HP threshold. Proposes [FleeFrom].
    Flee,
    /// Check ability priorities/conditions. Proposes [CastAbility].
    UseAbility,
    /// Follow party leader. Proposes [FollowEntity].
    FollowLeader { leader: Entity },
    /// Defend self when attacked (threat table non-empty). Proposes [EngageTarget].
    DefendSelf,
    /// Fallback. Proposes nothing.
    Idle,
}

impl TaskEvaluator {
    pub fn category(&self) -> EvaluatorCategory {
        match self {
            Self::EngageCombat | Self::Flee | Self::UseAbility | Self::DefendSelf => {
                EvaluatorCategory::Combat
            }
            Self::FollowLeader { .. } | Self::Idle => EvaluatorCategory::Routine,
        }
    }
}

/// How often combat evaluators run (in ticks).
pub const COMBAT_EVAL_INTERVAL: u32 = 5;
/// How often routine evaluators run (in ticks).
pub const ROUTINE_EVAL_INTERVAL: u32 = 60;

/// AI decision-making brain. Only on NPC entities.
/// Holds evaluator configuration, cooldowns, and proposal staging.
#[derive(Component, Clone, Debug)]
pub struct AiBrain {
    /// Which evaluators this entity uses.
    pub evaluators: Vec<TaskEvaluator>,
    /// Ticks until next combat evaluator run.
    pub combat_eval_cooldown: u32,
    /// Ticks until next routine evaluator run.
    pub routine_eval_cooldown: u32,
    /// Proposals from evaluators this tick. Cleared each evaluation cycle.
    pub proposals: Vec<Task>,
}

impl AiBrain {
    pub fn new(evaluators: Vec<TaskEvaluator>) -> Self {
        Self {
            evaluators,
            combat_eval_cooldown: 0,
            routine_eval_cooldown: 0,
            proposals: Vec::new(),
        }
    }

    /// Standard enemy brain.
    pub fn enemy() -> Self {
        Self::new(vec![
            TaskEvaluator::Flee,
            TaskEvaluator::UseAbility,
            TaskEvaluator::EngageCombat,
            TaskEvaluator::Idle,
        ])
    }
}
